### ISSUE TITLE
Failure to installing quanteda.textplots.

### ISSUE THREAD

**Issue by alamsyah78** [quanteda/quanteda.textplots#19]
Dear all,

I fail to install `quanteda.textplots` in R Studio. I used R version "Spotted Wakerobin" Release (34ea3031, 2022-07-06) for macOS. However, I successfully install `quanteda`, `quanteda.textmodels`, and `quanteda.textstats`. I captured my screen. I help you can help me to solve this problem.

Regards,

<img width="809" alt="quanteda textplot error" src="https://user-images.githubusercontent.com/16342588/188039909-ae1c6c47-8aad-473f-8225-2dd53e13edbb.png">

**Comment by kbenoit** [comment]
I just updated quanteda and quanteda.textmodels this week. It looks like you are trying to install quanteda.textmodels from source, which will not work if you don't have gfortran installed. I suggest you say No if it asks if you want to install from source. The macOS binary should be built in a day or so and then will install without needing compilation on your end.
